title: Bilel Mezhoud 
logo: /assets/img/1732825124596.jpg

description: "Welcome to my portfolio! I’m a Data Scientist and Machine Learning enthusiast who loves turning data into insights. Check out my skills, work, and projects, and let’s see what we can achieve together!"
theme: jekyll-theme-minimal
social_links:
  - name: LinkedIn
    url: https://www.linkedin.com/in/bilel-mezhoud/
  - name: GitHub
    url: https://github.com/BilelMezhoud

# SEO and metadata settings
seo:
  title: "Bilel Mezhoud - Data Scientist & Machine Learning Professional"
  description: "Explore my portfolio showcasing projects in AI, GIS, and software development."
  twitter_card: summary_large_image
